[project]
name = "my_project"
version = "0.1.0"
description = "Description of my project"
readme = "README.md"
requires-python = "==3.12.11"

dependencies = [
    "langchain==0.3.27",
    "azure-search-documents==11.5.3",
    "azure-identity==1.24.0",
    "openai==1.104.2",
    "langchain_core==0.3.75",
    "dotenv==0.9.9",
    "langchain_openai==0.3.32",
    "ftfy==6.3.1"
]

[project.optional-dependencies]
dev = [
    "ruff==0.12.11",
    "pre-commit==4.3.0"
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812", 
]

pydocstyle.convention = "google"