apiVersion: v1 # Kubernetes API version
kind: Service # declares the resource type as a Service
metadata:
  name: {{ .Values.fullnameOverride }}-api
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Values.labels.appName }}
    app.kubernetes.io/instance: {{ .Values.labels.instance }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Values.managedBy }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - name: http
    port: {{ .Values.api.service.port }}
    targetPort: 8000
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.labels.appName }}
    app.kubernetes.io/instance: {{ .Values.labels.instance }}
    app.kubernetes.io/component: api
