apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-kafka
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Values.labels.appName }}
    app.kubernetes.io/instance: {{ .Values.labels.instance }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Values.managedBy }}
    app.kubernetes.io/component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
  - name: internal
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: external
    port: 9094
    targetPort: 9094
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.labels.appName }}
    app.kubernetes.io/instance: {{ .Values.labels.instance }}
    app.kubernetes.io/component: kafka
