apiVersion: v1 # Kubernetes API version 1, which includes basic resources like Services
kind: Service # declares the resource type as a Service
metadata:
  name: {{ .Values.fullnameOverride }}-api # sets the name of the Service using `fullnameOverride` value from Helm values
  labels: # standard Kubernetes labels for better resource management and identification
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Values.labels.appName }}
    app.kubernetes.io/instance: {{ .Values.labels.instance }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Values.managedBy }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }} # defines the type of Service for API (i.e., LoadBalancer, exposing the API externally via Azure Load Balancer)
  {{- if .Values.api.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.api.service.loadBalancerSourceRanges }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  sessionAffinity: ClientIP # ensures requests from the same client IP are routed to the same pod (fixes session management issue)
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800 # 3 hours - session affinity timeout
  ports:
  - name: http
    port: {{ .Values.api.service.port }}
    targetPort: 8000
    protocol: TCP
  selector: # selects the pods to route traffic to, based on labels
    app.kubernetes.io/name: {{ .Values.labels.appName }}
    app.kubernetes.io/instance: {{ .Values.labels.instance }}
    app.kubernetes.io/component: api
